version: "3.8"

services:
  api:
    image: golang:1.20.3-alpine3.17
    container_name: api
    tty: true
    ports:
      - "8086:8080"
    volumes:
      - ./:/go/api
    working_dir: /go/api
    # command: go run main.go